### ISSUE TITLE
Feature: REST API to consume incoming messages

### ISSUE THREAD

**Issue by cwolchesky** [cwolchesky/snowflake#1]
Need to create a REST API to consume incoming messages to be relayed to the device.

## TODO

- [ ] Build out URL structure using express
- [ ] Consume incoming POST requests
- [ ] Relay incoming messages to Azure IoT Hub
